django_q/conf.py

Instead of checking if the django-q logger has any handlers directly, use the hasHandlers [1] method, which will check if any parent loggers have handlers as well.
This fixes a bug where django-q configures it's own logging even though the root logger has a handler set
1. https://docs.python.org/3/library/logging.html#logging.Logger.hasHandlers

Use logger.hasHandlers() to setup fallback logging

---

README.rst
docs/group.rst
docs/install.rst

- fix django q2 install command and remove space
- remove warnings for very old versions

Fix install command and remove old warnings

---

django_q/cluster.py
django_q/tests/test_cluster.py

Previously the error was this: 
```
14:03:49 [Q] ERROR Failed task (carpet-network-sodium-nevada) - 'NoneType' object is not callable : Traceback (most recent call last):
File "/app/django_q/cluster.py", line 439, in worker
res = f(*task["args"], **task["kwargs"])
TypeError: 'NoneType' object is not callable
```
Now it's this:
```
ERROR Failed djq.views.task (fish-glucose-hot-stream) - Could not process 'djq.views.task'. Check the location of the function and the args/kwargs.
```

Fix unclear error when function is not called correctly

---

CHANGELOG.md
django_q/core_signing.py

Move baseconv/base62 deprecation warning for Django 5.x

---

django_q/cluster.py
django_q/tests/test_scheduler.py
django_q/utils.py

For some reason, I was under the assumption that pytz was a required lib by Django and the default. But it's not and it's actually deprecated. The default is `zoneinfo` for Django 4.x and higher, which I have now used to replace pytz with.
Django allows for a setting to use `pytz`, so I have enabled that as well for this library:
https://github.com/django/django/blob/2d676ee119696250a8b76c69ec9d9b799ddeb6b4/django/utils/timezone.py#L71-L82
Edit: it's required for Django 3.2, and it's not in Django 4.x

Remove pytz dependency

---

django_q/models.py
django_q/tests/test_scheduler.py

Forgot to add test for when we DST ends. This triggered a bug when moving in that direction (normally in Oct/Nov).

Fix DST (move from DST to normal)

---

pyproject.toml

Fix missing setup file for "No matching distribution" error

---

pyproject.toml

Update needed to `pyproject.toml` to work with latest poetry version. 
Error: 
```
The Poetry configuration is invalid:
- [extras.requires.0] 'poetry_core>=1.0.0' does not match '^[a-zA-Z-_.0-9]+$'
```

Remove version locking on poetry_core to fix regex error

---

django_q/cluster.py
django_q/signals.py

Add a `post_spawn` signal that is sent from the worker function. The goal here is to give us a place to do something exactly one per worker, like initialize telemetry.

Add post_spawn signal.

---

django_q/cluster.py
docs/cluster.rst

Before this PR, it would show:
```
10:57:40 [Q] INFO Q Cluster vermont-cold-tennis-fish starting.               
10:57:40 [Q] INFO Process-1:1 ready for work at 31784
10:57:40 [Q] INFO Process-1:2 ready for work at 31785
10:57:40 [Q] INFO Process-1:3 monitoring at 31792
10:57:40 [Q] INFO Process-1 guarding cluster at 31783
10:57:40 [Q] INFO Process-1:4 pushing tasks at 31793
10:57:40 [Q] INFO Q Cluster vermont-cold-tennis-fish [DjangORM] running.
```
The `Process-1:1` is the name of the process of one of the workers. When the server is restarted, it would start again with those process names. So these cannot be used as a means of identification for longer than the process exists.
This can cause issues in two scenarios:
- Doing logging/`grep` on the process name to see what a worker has …

Make processes identifiable with uuid4

---

django_q/admin.py
django_q/tests/test_admin.py

It is often useful to be able to easily re-run a successful task via the admin interface.
Along with this feature implementation, to keep the code DRY I have updated the retry failed admin class to use the same `resubmit_task` function since they are nearly identical except for the fact that when we retry a failed task, we want to delete the original failure.

Rerun successful tasks

---

django_q/conf.py
poetry.lock
pyproject.toml

List entry points using `importlib.metadata` (Python >=3.10) or `importlib-metadata>=3.6` (Python < 3.10).
See compatibility notes in https://docs.python.org/3/library/importlib.metadata.html#entry-points.

Remove deprecated usage pkg_resources

---

docs/examples.rst
docs/monitor.rst

The health check example in the docs had a bad import for `Stat`. It worked while the `monitor` file was importing `Stat`, but as of 1.5.5 this no longer works.

DOCS: Correct health check import in examples.rst

---

docs/install.rst

Replace `pip install django-q[{name}]` to `pip install django-q2[{name}]`. Because of avoiding unnecessary dependencies installation.

Docs: Update Add-ons install command in install.rst

---

django_q/locale/de/LC_MESSAGES/django.po

Fixing a typo in the german translation .po file.

Fix German Translation Typo

---

pyproject.toml

Otherwise, trying to build the project with a tool like gpep517 or build results in using the setuptools legacy backend instead

Specify build system in pyproject.toml

---

django_q/core_signing.py

Use importerror for b62_decode to avoid deprecation notification

---

django_q/scheduler.py

Hello Folks,
The line of code s.repeats += -1 in the scheduler function has been commented out. This change is based on the understanding that s.repeats is incorrectly used as a counter for the number of executions of a task, which results in negative values once the task has been executed more times than initially scheduled.
Best Regards
Tobias

Fix for Negative Repeat Count in Scheduler (#101)

---

django_q/monitor.py

When using the value 1 for `max_attempts` it would create the `Task` on the failed attempt, but it would not check if the task should be pulled from the queue. The next worker would pick it up and after the second attempt, the task would get updated and it would then get pulled from the queue. It should have stopped at the first attempt.
This only happens with brokers that need acknowledgement of the task being completed.
The logic to decide if the task should be pulled from the queue is now triggered on both events.

Fix max attempts for value 1

---

.github/workflows/test.yml
django_q/exceptions.py
django_q/monitor.py
django_q/timeout.py
django_q/worker.py
docs/configure.rst

Timeouts that happened with brokers that need acknowledging could have jobs that would keep retrying. This was caused due to the process being killed without sending the job back to the `monitor` function that would mark the job as failed and would pull the task from the broker. This wasn't an issue with brokers that automatically remove the task from the broker when it gets pulled.
I have implemented a context manager that will keep track of the time in the worker itself (so not by the guard function). It will end the running task and return a timeout error. That gets caught and then it gets pushed to the monitor to process.
It will also set the timeout to 0, so the guard can clean the process up and reincarnate a process (so we get a clean state for the next task).

Fix repeating task after timeout

---

.github/workflows/test.yml

Django 5.1 was released
https://www.djangoproject.com/weblog/2024/aug/07/django-51-released/

chore: Add Support Django 5.1

---

django_q/cluster.py
django_q/conf.py

According to [documentation](https://prometheus.github.io/client_python/multiprocess/) of Prometheus client (see "3. Gunicorn configuration"), if you are using multiprocessing, and your process exits (ends, dies etc.), you need to notify Prometheus about the fact.

Call mark_process_dead on the dead worker if prometheus_client is installed

---

django_q/timeout.py

Need both `ValueError` to catch `signal.signal` not available and `AttributeError` to catch `signal.SIGALRM` missing.
Fixes #227 introduced by #223

Fix try-catch for Windows

---

django_q/scheduler.py

Minor fix for Ruff complaint:
```plain
django_q\scheduler.py:68:24: E721 Use `is` and `is not` for type comparisons, or `isinstance()` for isinstance checks
|
66 |                     args = ast.literal_eval(s.args)
67 |                     # single value won't eval to tuple, so:
68 |                     if type(args) != tuple:
|                        ^^^^^^^^^^^^^^^^^^^ E721
69 |                         args = (args,)
70 |                 q_options = kwargs.get("q_options", {})
```

Fix type check for args in scheduler.py E721

---

django_q/tests/test_cluster.py

Hello,
A long time ago, I opened https://github.com/Koed00/django-q/issues/649 against django-q, because when building django-q in Debian I was having unexplained failures on armhf architectures on `test_max_rss`. After some poking and reading I discovered that `armhf` architecture is very memory efficient and therefore with a 400k RSS, the expected recycling which had been designed for `amd64` architectures was not occurring.
This MR is a fix I implemented in Debian to ensure the test works consistently on all archs.
I think it'd be a nice addition.
Bests!

Decrease the MAX_RSS set in test_cluster::test_max_rss

---

Dockerfile.dev
containers/localstack/init.sh
django_q/brokers/aws_sqs.py
django_q/tests/test_brokers.py
test-services-docker-compose.yaml

The parameter `receive_message_wait_time_seconds` for the SQS broker is being removed when a new Boto connection/Session is created, and then `dequeue` operation cannot use it.
When the broker is created, a [new Boto connection via Session](https://github.com/django-q2/django-q2/blob/337a5782d9113a6e9d058743488e7517aebb8280/django_q/brokers/__init__.py#L13) is instantiated:
```
self.connection = self.get_connection(list_key)
```
This get_connection [retrieves the SQS configuration and removes data that is not accepted by the Session](https://github.com/amegianeg/django-q2/blob/master/django_q/brokers/aws_sqs.py#L86-L95):
```
def get_connection(list_key: str = None) -> Session:
config = Conf.SQS
if "aws_region" in config:
config["region_name"] = config["aws_region"]
del …
```

Fix 'receive_message_wait_time_seconds' SQS broker management

---

pyproject.toml

The file should not be installed directly in site-packages. Use the correct include syntax to include them into the source distribution package only.
This was noticed while packaging django-q2 for Gentoo. The automated QA checking noticed that the CHANGELOG.md file would be installed into the site-packages root directory, which is wrong.
See here for details from the Gentoo QA Team: https://projects.gentoo.org/python/guide/qawarn.html#stray-top-level-files-in-site-packages and here for how to use the install directive https://python-poetry.org/docs/pyproject/#include-and-exclude.
This will fix the issue.

Fix install path for CHANGELOG.md

---

Makefile
django_q/monitor.py
django_q/tests/test_cluster.py

We disabled save limit which generate a lot of wait time for each save ~20seconds

perf: avoid checking success tasks when save limit is disabled

---

.github/workflows/test.yml

Poetry version 2.0.0 seems to be causing issues in our CI. https://github.com/django-q2/django-q2/actions/runs/12729066315/job/35480632093

Fix poetry version in CI

---

django_q/__init__.py
django_q/models.py

- Removed registering of `default_app_config`, which isn't needed anymore after django version 3.2
- Removed safe decode for versions below django 1.7

Delete deprecated imports and unwrapping

---

.github/workflows/test.yml
README.rst
django_q/admin.py
django_q/models.py
pyproject.toml

1. Drop support for Python 3.8 which is EOL.
2. Add support for Python 3.13.
3. Add support for Django 5.2, currently in beta and [expected April](https://docs.djangoproject.com/en/5.2/releases/5.2/).

Update tested versions

---

django_q/tests/settings.py

This is needed for the tests to work when using a recent version of redis-py

Fix to work with redis-py > 5
