django-q2/django-q2

- .github/workflows/test.yml
- README.rst
> Codecov -> Coveralls

- django_q/locale/tr/LC_MESSAGES/django.po
> Feat: Turkish translations

- django_q/admin.py
- django_q/cluster.py
- django_q/conf.py
- django_q/models.py
Full details: https://github.com/Koed00/django-q/pull/605
> Admin improvements

- .github/FUNDING.yml
- Dockerfile
- django_q/cluster.py
- web-docker-compose.yaml
> Remove funding file, add docker/compose for development project and fix

- docs/install.rst
> Fix install docs: update q to q2

- django_q/cluster.py
- django_q/models.py
- django_q/utils.py
> Fix: func reference in admin

- django_q/cluster.py
- django_q/conf.py
- django_q/models.py
- django_q/tests/settings.py
- django_q/tests/test_scheduler.py
- django_q/utils.py
- docs/configure.rst
fixes #44
Still needs a bit more testing, but the new test passes, so it looks like this is close to merging.
To do:
> Fix daylight saving time issue with scheduler

- django_q/cluster.py
- django_q/tests/test_cluster.py
> Fix handling inner exceptions

- django_q/cluster.py
Improve log messages in case of exception.
Also log the name of the task that has been created from a schedule. This is useful to understand the lifecycle of a particular task.
> More explicit log messages in exception handling

- django_q/brokers/orm.py
This simple PR changes the _timeout() logic of the orm broker.
The objective is to have the lock datetime field as the intended execution time:
- tasks with lock > now() are not yet due for execution
- tasks with lock <= now() are past due for execution and will be pushed to workers at the next poll
Compared to current implementation :
- tasks with lock > (now() - Conf.RETRY) are not yet due for execution
- tasks with lock <= (now() - Conf.RETRY) are past due for execution
This makes reading the lock datetime much more intuitive when Conf.RETRY != 0.
> Change task timeout logic to have now() as execution time

- django_q/cluster.py
- django_q/conf.py
- django_q/tests/test_scheduler.py
- django_q/tests/testing_utilities/multiple_database_routers.py
- docs/configure.rst
Merge request following discussion on issue #60
> Fix use of database router for write queries and remove Conf.HAS_REPLICA

- .readthedocs.yaml
> Allow building all formats

- docs/signals.rst
#93 implemented the new post spawn signal, but I should have mentioned to add something to the docs. Fixed that with this PR.
> Worker post spawn signal documentation

- django_q/tasks.py
- django_q/tests/tasks.py
- django_q/tests/test_cluster.py
- docs/tasks.rst
> Fix not picking up result from falsy result

- docs/install.rst
> Add documentation to migrate from django-q to django-q2

- django_q/cluster.py
- django_q/monitor.py
- django_q/pusher.py
- django_q/scheduler.py
- django_q/worker.py
Fixes #109 
Still need to test this, but I have high hopes that this will fix the issue.
> Fix for apps not ready

- django_q/locale/fr/LC_MESSAGES/django.po
> Update french translations

- docs/tasks.rst
> Update docs to add cluster option to the async_task

- django_q/tasks.py
- docs/chain.rst
> Allow different broker on chain

- django_q/monitor.py
To fix #180 , this approach it's mainly added by @germancollado
> fix: Oracle ORM backend compatibility #180

- django_q/timeout.py
> Change ValueError with AttributeError in time out for SIGALRM

- django_q/cluster.py
If it is ok, can you generate a new version to us? Thanks.
> fix prometheus integration

- django_q/monitor.py
> workaround missing ack_id

- django_q/tests/test_brokers.py
Hey,
A long time ago, I opened this issue against django-q: https://github.com/Koed00/django-q/issues/644
I did a fix that is in this MR and was working for me.
IDK if that's of interest for you.
Bests,
> Fix BROKER_CLASS monkeypatch in test_brokers

- .github/workflows/test.yml
Missed when removing disque support in #17.
> Remove disque from CI

- django_q/models.py
- django_q/tests/test_scheduler.py
Fixes #235. Closes #236.
@GDay could you check if the tests I've made are sufficient for this case? If possible, could you test in your web server? I'd issues setting up locally, I could only run the test suite through `make`, I will seek into this setup problem and communicate with you later.
> Avoid creating task run on Scheduler creation
